app/blueprints/main/models.py
from app import db, login_manager
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(50), unique=True)
    username = db.Column(db.String(50))
    password = db.Column(db.String(200))
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))

    def hash_my_password(self, password):
        self.password = generate_password_hash(password)

    def check_my_password(self, password):
        return check_password_hash(self.password, password)

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(250))
    body = db.Column(db.String(1200))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    date_created = db.Column(db.DateTime, default=datetime.utcnow)

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class Pokemon(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    description = db.Column(db.String(1040))
    typing = db.Column(db.String(100))
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class Collection(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    description = db.Column(db.String(1040))
    typing = db.Column(db.String(100))
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)
    # Connecting our config class and our flask application
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    from app.blueprints.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.blueprints.api import bp as api_bp
    app.register_blueprint(api_bp)

    from app.blueprints.auth import bp as auth_bp
    app.register_blueprint(auth_bp)

    return app

app/blueprints/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__, url_prefix="/api")

from . import models, routes

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__, url_prefix="/")

from . import models, routes

app/blueprints/main/routes.py
from . import bp as app
from flask import render_template, request, redirect, url_for, flash
from app.blueprints.main.models import User, Post, Pokemon, Collection
from app import db
from flask_login import current_user, login_required

# Routes that return/display HTML

@app.route('/')
@login_required
def home():
    posts = Post.query.all()
    return render_template('home.html', user=current_user, posts=posts)

@app.route('/user/<username>')
@login_required
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.all()
    pokes = Pokemon.query.all()
    return render_template('user.html', user=user, posts=posts, pokes=pokes)

@app.route('/pokemon')
@login_required
def pokemon():
    pokes = Pokemon.query.all()
    return render_template('pokemon.html', user=current_user, pokes=pokes)

@app.route('/about')
@login_required
def about():
    return render_template('about.html')

@app.route('/contact')
@login_required
def contact():
    return render_template('contact.html')

@app.route('/post', methods=['POST'])
@login_required
def create_post():
    post_title = request.form['title']
    post_body = request.form['body']
    
    new_post = Post(title=post_title, body=post_body, user_id=current_user.id)

    db.session.add(new_post)
    db.session.commit()

    flash('Post added successfully', 'success')
    return redirect(url_for('main.home'))

@app.route('/post/<id>')
def post(id):
    single_post = Post.query.get(id)
    return render_template('single-post.html', post=single_post)

#pokemon listings

@app.route('/pokecreate', methods=['POST'])
@login_required
def create_pokemon():
    poke_name = request.form['name']
    poke_description = request.form['description']
    poke_typing = request.form['type']
    
    new_poke = Pokemon(name=poke_name, description=poke_description, typing=poke_typing, user_id=current_user.id)

    db.session.add(new_poke)
    db.session.commit()

    flash('Pokemon has been added!!!', 'success')
    return redirect(url_for('main.pokemon'))

@app.route('/pokeentry/<id>')
def pokeentry(id):
    pokemon_entry = Pokemon.query.get(id)
    return render_template('poke_entry.html', user=current_user, pokeentry=pokemon_entry)


@app.route('/pokecatch')
def catchpoke():
    poke_name = request.form['name']
    poke_description = request.form['description']
    poke_typing = request.form['type']
    
    catch = Collection(name=poke_name, description=poke_description, typing=poke_typing, user_id=current_user.id)

    db.session.add(catch)
    db.session.commit()

    flash('You Caught a New Pokemon!!!', 'success')
    return redirect(url_for('main.pokemon'))

app/templates/about.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>About</h1>


<h4>English</h4>
<p> Welcome to the World of Pokemon. And most importantly, welcome to my project. This took a good while to
    set up, so I hope you like it if you pass through here.
</p>


<h4>Español</h4>
<p> Hola, seguidores de mi Telegram y otras redes sociales con las que he compartido esto. Espero que les guste
    lo que he construido aqui. Esto una practica para ver como he avanzado con mis estudios. Si pudieras pasar
    y agregar algunos Pokemon que conozcas, seria genial!!! Tambien puedes publicar un comentario. 
    mantengalo PG, que esto es tarea que estare entregando. Asi que no se pasen X'D
</p>

{% endblock content %}

app/templates/home.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>Welcome to The World of Pokemon!!!</h1>
<p>Welcome {{ user['first_name'] }} {{ user['last_name'] }}.</p>

<h2>Create Post</h2>
<form action="{{ url_for('main.create_post') }}" method="POST" class="my-2">
  <div class="form-group">
    <label for="title">Title</label>
    <input type="text" class="form-control" id="title" name="title">
  </div>
  <div class="form-group">
    <label for="body">Body</label>
    <input type="text" class="form-control" id="body" name="body">
  </div>
  <button type="submit" class="btn w-25 mt-4" style="background-color: #767d92;">Submit</button>
</form>

{% for post in posts %}
<div class="card mb-2">
  <div class="card-header">
    <a href="{{ url_for('main.post', id=post['id']) }}">{{ post['title'] }}</a>
  </div>
</div>
{% endfor %}
{% endblock content %}

app/templates/login.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>Login</h1>
<form action="{{ url_for('auth.login') }}" method="POST">
    {{ form.hidden_tag() }}
    <fieldset id="username-field">
        {{ form.user_name.label }}
        {{ form.user_name(class="form-control", placeholder = "Enter your Username here") }}
    </fieldset>
    <div class="form-group">
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder = "Enter your password here") }}
        </fieldset>
    </div>
    <p><small>Don't have an account? <a href="{{ url_for('auth.register') }}">Register here.</a></small></p>

    {{ form.submit(class = "btn btn-primary btn-block") }}
</form>
{% endblock content %}

app/templates/partials/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Pokemon</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        
</head>

<body class="text-center" style="color: #f4d47c;">
    <header class="mb-5">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">LynxPokemon</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('main.home') }}">Home<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.pokemon') }}">Pokemon</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if not current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.user', username=current_user.username) }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    
    </header>
<style>
    body{
    background-image: url('https://i.kym-cdn.com/photos/images/original/002/268/960/664');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    }
</style>
    <main class="container p-5 " style="background-color: #081b3399; border-radius: 25px;" >
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <!-- THIS IS WHERE WE WILL PUT EACH PAGE'S CONTENT -->
        {% block content %}{% endblock content %}
    </main>

    <!-- <footer>
        This is a footer
    </footer> -->
</body>

</html>

app/templates/poke_entry.html
{% extends './partials/layout.html' %}

{% block content %}
<div class="card p-3 m-5" style="background-color: #081b33; border-radius: 25px;">
    <div class="card-header border-bottom border-dark">
        <h2> {{ pokeentry['name'] }}</h2>
    </div>
    <div class="card-body">
        <h5>Description: {{ pokeentry['description'] }}</h5>
    </div>
    <div class="card-body">
        <h5>Typing: {{ pokeentry['typing'] }}</h5>
    </div>
    <div class="card-body">
       <h5>Owner: {{ user['username'] }}</h5>
    </div>
</div>
{% endblock content %}

app/templates/pokemon.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>Pokemon</h1>
<p>Welcome {{ user['first_name'] }} {{ user['last_name'] }}.</p>

<h2>Add a Pokemon</h2>
<form action="{{ url_for('main.create_pokemon') }}" method="POST" class="my-2">
    <div class="form-group">
        <label for="name">name</label>
        <input type="text" class="form-control" id="name" name="name">
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <input type="text" class="form-control" id="description" name="description">
    </div>
    <div class="form-group">
        <label for="type">Type</label>
        <input type="text" class="form-control" id="type" name="type">
    </div>
    <button type="submit" class="btn w-25" style="background-color: #767d92;">Add Pokemon</button>
</form>


{% for poke in pokes %}
<div class="card p-3 m-5" style="background-color: #081b33; border-radius: 25px;">
    <h3>{{ poke['name'] }}</h3>
    <a type="button" class="btn my-2" style="background-color: #767d92;" href="{{ url_for('main.pokeentry', id=poke['id']) }}">Pokedex</a>
    <a type="button" class="btn my-2" style="background-color: #767d92;" action="{{ url_for('main.catchpoke') }}">Catch</a>
</div>
{% endfor %}
{% endblock content %}

app/templates/register.html
{% extends './partials/layout.html' %}

{% block content %}
<h1>Register</h1>
<form action="{{ url_for('auth.register') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class="form-control", placeholder = "Enter your Email here") }}
        </fieldset>

        <!-- <label for="inputEmail">Email address</label>
        <input type="email" class="form-control" id="inputEmail" name="inputEmail" aria-describedby="emailHelp"> -->
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class="form-control", placeholder = "Enter your username here") }}
        </fieldset>

        <!-- <label for="inputUsername">Username</label>
        <input type="text" class="form-control" id="inputUsername" name="inputUsername"> -->
    </div>
    <div class="form-group">
        <fieldset id="first_name-field">
            {{ form.first_name.label }}
            {{ form.first_name(class="form-control", placeholder = "Enter your First Name here") }}
        </fieldset>
        <!-- <label for="inputFirstName">First Name</label>
        <input type="text" class="form-control" id="inputFirstName" name="inputFirstName"> -->
    </div>
    <div class="form-group">
        <fieldset id="last_name-field">
            {{ form.last_name.label }}
            {{ form.last_name(class="form-control", placeholder = "Enter your Last Name here") }}
        </fieldset>
        <!-- <label for="inputLastName">Last Name</label>
        <input type="text" class="form-control" id="inputLastName" name="inputLastName"> -->
    </div>
    <div class="form-group">
        <fieldset id="password-field">
            {{ form.password.label }}
            {{ form.password(class="form-control", placeholder = "Enter your password here") }}
        </fieldset>

        <!-- <label for="inputPassword">Password</label>
        <input type="password" class="form-control" id="inputPassword" name="inputPassword"> -->
    </div>
    <div class="form-group">

        <fieldset id="confirm_password-field">
            {{ form.confirm_password.label }}
            {{ form.confirm_password(class="form-control", placeholder = "Confirm your password here") }}
        </fieldset>

        <!-- <label for="inputPasswordConfirm">Confirm Password</label>
        <input type="password" class="form-control" id="inputPasswordConfirm" name="inputPasswordConfirm"> -->
    </div>
    <p><small>Already have an account? <a href="{{ url_for('auth.login') }}">Login here.</a></small></p>
    {{ form.submit_button(class = "btn btn-primary btn-block") }}
    <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
</form>
{% endblock content %}

app/templates/single-post.html
{% extends './partials/layout.html' %}

{% block content %}
<div class="card">
    <div class="card-header">
        {{ post['title'] }}
    </div>
    <div class="card-body">
        {{ post['body'] }}
    </div>
</div>
{% endblock content %}

app/templates/user.html
{% extends './partials/layout.html' %}

{% block content %}
    <h1>User/Usuario: {{ user.username }}</h1>
    <hr>
    {% for post in posts %}
    <p>
    {{ post.title }} says: <b>{{ post.body }}</b>
    </p>
    {% endfor %}

    {% for poke in pokes %}
    <div class="card p-3 m-5" style="background-color: #081b33; border-radius: 25px;">
        <h3>{{ poke['name'] }}</h3>
        <a type="button" class="btn my-2" style="background-color: #767d92;" href="{{ url_for('main.pokeentry', id=poke['id']) }}">Pokedex</a>
    </div>

    {% endfor %}
{% endblock %}